apiVersion: v1
kind: PersistentVolume
metadata:
  name: todos-pv
spec:
  storageClassName: todos-pv
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rke2-worker-01-192
